version: '3.9'
services:
    web:
        build: .
        command: python3 /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
          db:
            condition: service_healthy
        env_file:
            - .env
    db:
        image: mysql:8.1.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password --mysqlx=0
        environment:
            MYSQL_DATABASE: ecommerce
            MYSQL_USER: clothuser
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ".dbdata:/var/lib/mysql"
        ports:
            - '3305:3306'
        env_file:
            - .env

        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
          interval: 10s
          timeout: 5s
          retries: 5
